name: DAG tests

on:
  pull_request:


jobs:
  test-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt

      - name: Get changed files
        # id нужен для обращения к результату
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          separator: " "

      # запуск с переменной содержащей список измененных файлов
      - name: Run tests
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}" python -m pytest tests/